[package]
name = "cowcord"
version = "0.0.1"
edition = "2024"

[dependencies]
dioxus = { version = "0.7.3", features = ["router", "desktop"] }
reqwest = { version = "0.12.15", features = ["json", "blocking", "multipart"] }
serde = "1.0.219"
serde_json = "1.0.140"
keyring = "3.6.3"
discord-api = { workspace = true }
tailwind_fuse = "0.3.2"
